cities = [
    ('AK/Anchorage', 'Anchorage'),
    ('AZ/Phoenix', 'Phoenix'),
    ('AZ/Tucson', 'Tucson'),
    ('AZ/Mesa', 'Mesa'),
    ('AZ/Chandler', 'Chandler'),
    ('AZ/Gilbert', 'Gilbert'),
    ('AZ/Glendale', 'Glendale'),
    ('AZ/Scottsdale', 'Scottsdale'),
    ('CA/Los_Angeles', 'Los Angeles'),
    ('CA/San_Diego', 'San Diego'),
    ('CA/San_Jose', 'San Jose'),
    ('CA/San_Francisco', 'San Francisco'),
    ('CA/Fresno', 'Fresno'),
    ('CA/Sacramento', 'Sacramento'),
    ('CA/Long_Beach', 'Long Beach'),
    ('CA/Oakland', 'Oakland'),
    ('CA/Bakersfield', 'Bakersfield'),
    ('CA/Anaheim', 'Anaheim'),
    ('CA/Santa_Ana', 'Santa Ana'),
    ('CA/Riverside', 'Riverside'),
    ('CA/Stokton', 'Stokton'),
    ('CA/Chula_Vista', 'Chula Vista'),
    ('CA/Irvine', 'Irvine'),
    ('CA/Fremont', 'Fremont'),
    ('CA/San_Bernardino', 'San Bernardino'),
    ('CO/Denver', 'Denver'),
    ('CO/Colorado_Springs', 'Colorado Springs'),
    ('CO/Aurora', 'Aurora'),
    ('DC/Washington', 'Washington'),
    ('FL/Jacksonville', 'Jacksonville'),
    ('FL/Miami', 'Miami'),
    ('FL/Tampa', 'Tampa'),
    ('FL/Orlando', 'Orlando'),
    ('FL/St_Petersburg', 'St Petersburg'),
    ('FL/Hialeah', 'Hialeah'),
    ('GA/Atlanta', 'Atlanta'),
    ('HI/Honolulu', 'Honolulu'),
    ('ID/Boise', 'Boise'),
    ('IL/Chicago', 'Chicago'),
    ('IN/Indianapolis', 'Indianapolis'),
    ('IN/Fort_Wayne', 'Fort Wayne'),
    ('KS/Wichita', 'Wichita'),
    ('KY/Louisville', 'Louisville'),
    ('KY/Lexington', 'Lexington'),
    ('LA/New_Orleans', 'New Orleans'),
    ('LA/Baton_Rouge', 'Baton Rouge'),
    ('MD/Baltimore', 'Baltimore'),
    ('MA/Boston', 'Boston'),
    ('MI/Detroit', 'Detroit'),
    ('MN/Minneapolis', 'Minneapolis'),
    ('MN/Saint_Paul', 'Saint Paul'),
    ('MO/Kansas_City', 'Kansas City'),
    ('MO/St_Louis', 'St Louis'),
    ('NE/Omaha', 'Omaha'),
    ('NE/Lincoln', 'Lincoln'),
    ('NV/Las_Vegas', 'Las Vegas'),
    ('NV/Henderson', 'Henderson'),
    ('NV/Reno', 'Reno'),
    ('NV/North_Las_Vegas', 'North Las Vegas'),
    ('NJ/Newark', 'Newark'),
    ('NJ/Jersey_City', 'Jersey City'),
    ('NM/Albuquerque', 'Albuquerque'),
    ('NY/New_York', 'New York'),
    ('NY/Buffalo', 'Buffalo'),
    ('NC/Charlotte', 'Charlotte'),
    ('NC/Raleigh', 'Raleigh'),
    ('NC/Greensboro', 'Greensboro'),
    ('NC/Durham', 'Durham'),
    ('NC/Winston_Salem', 'Winston Salem'),
    ('OH/Columbus', 'Columbus'),
    ('OH/Cleveland', 'Cleveland'),
    ('OH/Cincinnati', 'Cincinnati'),
    ('OH/Toledo', 'Toledo'),
    ('OK/Oklahoma_City', 'Oklahoma City'),
    ('OK/Tulsa', 'Tulsa'),
    ('OR/Portland', 'Portland'),
    ('PA/Philadelphia', 'Philadelphia'),
    ('PA/Pittsburgh', 'Pittsburgh'),
    ('TN/Memphis', 'Memphis'),
    ('TN/Nashville', 'Nashville'),
    ('TX/Houston', 'Houston'),
    ('TX/San_Antonio', 'San Antonio'),
    ('TX/Dallas', 'Dallas'),
    ('TX/Austin', 'Austin'),
    ('TX/Fort_Worth', 'Fort Worth'),
    ('TX/El_Paso', 'El Paso'),
    ('TX/Arlington', 'Arlington'),
    ('TX/Corpus_Christi', 'Corpus Christi'),
    ('TX/Plano', 'Plano'),
    ('TX/Laredo', 'Laredo'),
    ('TX/Lubbock', 'Lubbock'),
    ('TX/Garland', 'Garland'),
    ('TX/Irving', 'Irving'),
    ('VA/Virginia_Beach', 'Virginia Beach'),
    ('VA/Norfolk', 'Norfolk'),
    ('VA/Chesapeake', 'Chesapeake'),
    ('VA/Richmond', 'Richmond'),
    ('WA/Seattle', 'Seattle'),
    ('WI/Milwaukee', 'Milwaukee'),
    ('WI/Madison', 'Madison'),
]
